# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies & download spaCy model
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm

      - name: Run pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Build backend Docker image
        run: docker build -t skill-gap-backend -f Dockerfile.backend .

      - name: Build frontend Docker image
        run: docker build -t skill-gap-frontend -f Dockerfile.frontend .
